### ISSUE TITLE
Request for Video Showcase of Project on Any Popular Platform

### ISSUE THREAD

**Issue by Greatz08** [getmaxun/maxun#100]
Could you please create a proper video showcase of this project to demonstrate its functionality and features with any interesting example? A video would be a great way to highlight what’s been built and share it with a wider audience. Gif is good but complete video would be much better imo :-))

Thank you!

**Comment by amhsirak** [comment]
@Greatz08 Yes we will be adding multiple video demos. We were not expecting a lot of people to notice the project so decided to hold it but will do it ASAP 👍

**Comment by amhsirak** [comment]
@Greatz08 we've added a basic introductory tutorial to help you get started, covering producthunt.com, ycombinator.com and github.com : https://www.youtube.com/watch?v=ZXGQEwQN7yI&t=2s
