### ISSUE TITLE
Error by NPM Install

### ISSUE THREAD

**Issue by Octavious** [getmaxun/maxun#101]
I am following the instruction , and during npm install i get

m:\scrappingtrial\maxun\node_modules\msgpackr-extract\src\extract.cpp(166): error C2660: 'v8::Array::New': function doe
s not take 3 arguments [M:\scrappingTrial\maxun\node_modules\msgpackr-extract\build\extract.vcxproj]

**Comment by amhsirak** [comment]
@RohitR311 take a look

**Comment by amhsirak** [comment]
@Octavious hi, could you try using the docker compose file? if not, can you tell us the following:
- your operating system
- your IDE?

**Comment by Octavious** [comment]
Hi,

I'm not using dockers. (I am not an expert in dockers) 

My OS is Windows 11

I am not using an IDE

I simply worked in powershell and followed the instructions

Regs

**Comment by Octavious** [comment]
Hi, 

now on another PC, it seems to work, on http://localhost:5173/ i get a login page (i dont know what to do with it, but this is another story).

since this tool assumes no code knowledge, i propose that you enhance a bit how people can use it, i.e. enhance the step by step tutorial.

Good luck

Thanks

**Comment by amhsirak** [comment]
@Octavious our open-source version is for people who want to manage their infrastructure. I believe for you our hosted cloud version will be useful as you will not have to manage the infrastructure at all. We launch our cloud version soon, and for early access you can <a href="https://docs.google.com/forms/d/e/1FAIpQLSdbD2uhqC4sbg4eLZ9qrFbyrfkXZ2XsI6dQ0USRCQNZNn5pzg/viewform">join the waitlist here</a>

**Comment by Octavious** [comment]
@amhsirak thanks for the reply, i have registered to the wish list

meanwhile, what is your advice for the login :)?

**Comment by amhsirak** [comment]
@Octavious just register a user and you will auto login. With the same credentials you can login later. For how to train a robot, take a look here: https://www.youtube.com/watch?v=ZXGQEwQN7yI&t=11s
