### ISSUE TITLE
Can't execute start.sh for maxun-backend

### ISSUE THREAD

**Issue by KoutaTakeshi** [getmaxun/maxun#111]
Hi! I'm setting up the platform through docker-compose, during executing `docker-compose up -d --build`, everything seems normal, but after this I found only maxun-backend-1 can't boot up and the error message is as follows:
"exec ./start.sh: no such file or directory"
How can I fix this issue?

**Comment by amhsirak** [comment]
@KoutaTakeshi Is your docker cached? Can you clear cache and try? @RohitR311 had the same problem but clearing the cache helped

**Comment by ergun-acar** [comment]
The error you're seeing is due to start.sh having Windows-style line endings (CRLF) instead of Unix-style (LF). To fix this, you need to convert the line endings to Unix format so the script can run in the Linux-based Docker container.

**Comment by amhsirak** [comment]
@KoutaTakeshi Hi, we've just removed the start.sh script 
1. Pull the latest changes from the repository and build the docker compose 
2. If the issue persists, remove the container and all volumes associated with it. It might be due to cache - some people reported this

Do let me know if this works

**Comment by KoutaTakeshi** [comment]
> The error you're seeing is due to start.sh having Windows-style line endings (CRLF) instead of Unix-style (LF). To fix this, you need to convert the line endings to Unix format so the script can run in the Linux-based Docker container.

Unfortunately, it doesn't work, but thanks!

**Comment by KoutaTakeshi** [comment]
> @KoutaTakeshi Hi, we've just removed the start.sh script
> 
> 1. Pull the latest changes from the repository and build the docker compose
> 2. If the issue persists, remove the container and all volumes associated with it. It might be due to cache - some people reported this
> 
> Do let me know if this works

After pulling the latest changes and rebuild, it can work normally, thanks for your effort!
