### ISSUE TITLE
Sustainability of project: Are you looking for funding?

### ISSUE THREAD

**Issue by HarshGID100** [getmaxun/maxun#117]
Hi @amhsirak, have reached out over Discord for the same.
Maxun is extremely good, even in beta. Our team has been paying a screenshot API service for a long time, but we are going to switch to Maxun. Keep up the good work! 

We really would like to help the Maxun team in whatever way possible. Are you looking to raise funds?

**Comment by amhsirak** [comment]
@HarshGID100 Have messaged you on Discord.
