### ISSUE TITLE
Feature: Export to CSV

### ISSUE THREAD

**Issue by joshua111000** [getmaxun/maxun#119]

**Comment by blazingbhavneek** [comment]
Can I have it? Thanks!

**Comment by amhsirak** [comment]
@blazingbhavneek assigned 👍

**Comment by AmitChauhan63390** [comment]
![image](https://github.com/user-attachments/assets/e1106d8e-bc8a-49dc-bfdb-6cf0abf25d5e)

**Comment by amhsirak** [comment]
@joshua111000 available in <a href="https://github.com/getmaxun/maxun/releases/tag/v0.0.2">v0.0.2</a>
