### ISSUE TITLE
After clicking Start Training Bot it is only loading screen

### ISSUE THREAD

**Issue by chiranjivSharma** [getmaxun/maxun#129]
After I enter https://www.producthunt.com/ and click on Start Training Bot it shows only laoding page Spinning up a browser...Navigating to https://www.producthunt.com/ ,but doesn't go to the next page.

Below is the console log error.

socket__io-client.js?v=79231ad5:1059 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=4&transport=websocket' failed: 
createSocket @ socket__io-client.js?v=79231ad5:1059
doOpen @ socket__io-client.js?v=79231ad5:986
open @ socket__io-client.js?v=79231ad5:503
_open @ socket__io-client.js?v=79231ad5:1328
_SocketWithoutUpgrade @ socket__io-client.js?v=79231ad5:1289
SocketWithUpgrade @ socket__io-client.js?v=79231ad5:1633
Socket @ socket__io-client.js?v=79231ad5:1759
open @ socket__io-client.js?v=79231ad5:3125
(anonymous) @ socket__io-client.js?v=79231ad5:3343
Show 9 more frames
Show less
socket.tsx:36 connect_error due to websocket error
socket__io-client.js?v=79231ad5:1059 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=4&transport=websocket' failed: 
createSocket @ socket__io-client.js?v=79231ad5:1059
doOpen @ socket__io-client.js?v=79231ad5:986
open @ socket__io-client.js?v=79231ad5:503
_open @ socket__io-client.js?v=79231ad5:1328
_SocketWithoutUpgrade @ socket__io-client.js?v=79231ad5:1289
SocketWithUpgrade @ socket__io-client.js?v=79231ad5:1633
Socket @ socket__io-client.js?v=79231ad5:1759
open @ socket__io-client.js?v=79231ad5:3125
(anonymous) @ socket__io-client.js?v=79231ad5:3343
Show 9 more frames
Show less
socket.tsx:36 connect_error due to websocket error
socket__io-client.js?v=79231ad5:1059 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=4&transport=websocket' failed: 
createSocket @ socket__io-client.js?v=79231ad5:1059
doOpen @ socket__io-client.js?v=79231ad5:986
open @ socket__io-client.js?v=79231ad5:503
_open @ socket__io-client.js?v=79231ad5:1328
_SocketWithoutUpgrade @ socket__io-client.js?v=79231ad5:1289
SocketWithUpgrade @ socket__io-client.js?v=79231ad5:1633
Socket @ socket__io-client.js?v=79231ad5:1759
open @ socket__io-client.js?v=79231ad5:3125
(anonymous) @ socket__io-client.js?v=79231ad5:3343
Show 9 more frames
Show less
socket.tsx:36 connect_error due to websocket error
socket__io-client.js?v=79231ad5:1059 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=4&transport=websocket' failed: 
createSocket @ socket__io-client.js?v=79231ad5:1059
doOpen @ socket__io-client.js?v=79231ad5:986
open @ socket__io-client.js?v=79231ad5:503
_open @ socket__io-client.js?v=79231ad5:1328
_SocketWithoutUpgrade @ socket__io-client.js?v=79231ad5:1289
SocketWithUpgrade @ socket__io-client.js?v=79231ad5:1633
Socket @ socket__io-client.js?v=79231ad5:1759
open @ socket__io-client.js?v=79231ad5:3125
(anonymous) @ socket__io-client.js?v=79231ad5:3343
Show 9 more frames
Show less
socket.tsx:36 connect_error due to websocket error
socket__io-client.js?v=79231ad5:1059 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=4&transport=websocket' failed: 
createSocket @ socket__io-client.js?v=79231ad5:1059
doOpen @ socket__io-client.js?v=79231ad5:986
open @ socket__io-client.js?v=79231ad5:503
_open @ socket__io-client.js?v=79231ad5:1328
_SocketWithoutUpgrade @ socket__io-client.js?v=79231ad5:1289
SocketWithUpgrade @ socket__io-client.js?v=79231ad5:1633
Socket @ socket__io-client.js?v=79231ad5:1759
open @ socket__io-client.js?v=79231ad5:3125
(anonymous) @ socket__io-client.js?v=79231ad5:3343
Show 9 more frames
Show less
socket.tsx:36 connect_error due to websocket error
socket__io-client.js?v=79231ad5:1059 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=4&transport=websocket' failed: 
createSocket @ socket__io-client.js?v=79231ad5:1059
doOpen @ socket__io-client.js?v=79231ad5:986
open @ socket__io-client.js?v=79231ad5:503
_open @ socket__io-client.js?v=79231ad5:1328
_SocketWithoutUpgrade @ socket__io-client.js?v=79231ad5:1289
SocketWithUpgrade @ socket__io-client.js?v=79231ad5:1633
Socket @ socket__io-client.js?v=79231ad5:1759
open @ socket__io-client.js?v=79231ad5:3125
(anonymous) @ socket__io-client.js?v=79231ad5:3343
Show 9 more frames
Show less
socket.tsx:36 connect_error due to websocket error
socket__io-client.js?v=79231ad5:1059 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=4&transport=websocket' failed: 
createSocket @ socket__io-client.js?v=79231ad5:1059
doOpen @ socket__io-client.js?v=79231ad5:986
open @ socket__io-client.js?v=79231ad5:503
_open @ socket__io-client.js?v=79231ad5:1328
_SocketWithoutUpgrade @ socket__io-client.js?v=79231ad5:1289
SocketWithUpgrade @ socket__io-client.js?v=79231ad5:1633
Socket @ socket__io-client.js?v=79231ad5:1759
open @ socket__io-client.js?v=79231ad5:3125
(anonymous) @ socket__io-client.js?v=79231ad5:3343
Show 9 more frames
Show less
socket.tsx:36 connect_error due to websocket error
socket__io-client.js?v=79231ad5:1059 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=4&transport=websocket' failed: 
createSocket @ socket__io-client.js?v=79231ad5:1059
doOpen @ socket__io-client.js?v=79231ad5:986
open @ socket__io-client.js?v=79231ad5:503
_open @ socket__io-client.js?v=79231ad5:1328
_SocketWithoutUpgrade @ socket__io-client.js?v=79231ad5:1289
SocketWithUpgrade @ socket__io-client.js?v=79231ad5:1633
Socket @ socket__io-client.js?v=79231ad5:1759
open @ socket__io-client.js?v=79231ad5:3125
(anonymous) @ socket__io-client.js?v=79231ad5:3343
Show 9 more frames
Show less
socket.tsx:36 connect_error due to websocket error
socket__io-client.js?v=79231ad5:1059 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=4&transport=websocket' failed: 
createSocket @ socket__io-client.js?v=79231ad5:1059
doOpen @ socket__io-client.js?v=79231ad5:986
open @ socket__io-client.js?v=79231ad5:503
_open @ socket__io-client.js?v=79231ad5:1328
_SocketWithoutUpgrade @ socket__io-client.js?v=79231ad5:1289
SocketWithUpgrade @ socket__io-client.js?v=79231ad5:1633
Socket @ socket__io-client.js?v=79231ad5:1759
open @ socket__io-client.js?v=79231ad5:3125
(anonymous) @ socket__io-client.js?v=79231ad5:3343
Show 9 more frames
Show less
socket.tsx:36 connect_error due to websocket error
socket__io-client.js?v=79231ad5:1059 WebSocket connection to 'ws://localhost:8080/socket.io/?EIO=4&transport=websocket' failed: 
createSocket @ socket__io-client.js?v=79231ad5:1059
doOpen @ socket__io-client.js?v=79231ad5:986
open @ socket__io-client.js?v=79231ad5:503
_open @ socket__io-client.js?v=79231ad5:1328
_SocketWithoutUpgrade @ socket__io-client.js?v=79231ad5:1289
SocketWithUpgrade @ socket__io-client.js?v=79231ad5:1633
Socket @ socket__io-client.js?v=79231ad5:1759
open @ socket__io-client.js?v=79231ad5:3125
(anonymous) @ socket__io-client.js?v=79231ad5:3343
Show 9 more frames
Show less
socket.tsx:36 connect_error due to websocket error

Could you please help.

**Comment by chiranjivSharma** [comment]
2024-11-05T09:40:12.767Z warn: No active browser in the pool
[0] id start: 675534de-1706-4908-8493-b6aff02ebb37
[0] (node:32761) DeprecationWarning: uuidv4() is deprecated. Use v4() from the uuid module instead.
[0] (Use `node --trace-deprecation ...` to show where the warning was created)
[0] 2024-11-05T09:40:12.809Z info: Client connected 2mswWXNeN0jCb4qdAAAB
[0] 2024-11-05T09:40:12.810Z warn: No active browser in the pool
[0] /home/shivam/maxun-master/server/src/browser-management/classes/RemoteBrowser.ts:125
[0]         this.browser = <Browser>(await chromium.launch({
[0]                                                 ^
[0] browserType.launch: Executable doesn't exist at /home/shivam/.cache/ms-playwright/chromium-1140/chrome-linux/chrome
[0] ╔═════════════════════════════════════════════════════════════════════════╗
[0] ║ Looks like Playwright Test or Playwright was just installed or updated. ║
[0] ║ Please run the following command to download new browsers:              ║
[0] ║                                                                         ║
[0] ║     npx playwright install                                              ║
[0] ║                                                                         ║
[0] ║ <3 Playwright Team                                                      ║
[0] ╚═════════════════════════════════════════════════════════════════════════╝
[0]     at RemoteBrowser.initialize (/home/shivam/maxun-master/server/src/browser-management/classes/RemoteBrowser.ts:125:49)
[0]     at /home/shivam/maxun-master/server/src/browser-management/controller.ts:37:30
[0]     at Namespace.onConnection (/home/shivam/maxun-master/server/src/socket-connection/connection.ts:20:9)
[0]     at Namespace.emitReserved (/home/shivam/maxun-master/node_modules/socket.io/dist/typed-events.js:56:22)
[0]     at Namespace._doConnect (/home/shivam/maxun-master/node_modules/socket.io/dist/namespace.js:276:14)
[0]     at /home/shivam/maxun-master/node_modules/socket.io/dist/namespace.js:238:22 {
[0]   name: 'Error'
[0] }
[0] [nodemon] app crashed - waiting for file changes before starting...


and this I see in node application command line

**Comment by amhsirak** [comment]
The error is very clear. You've not installed playwright drivers. Just run thr command `npx playwright install`. @chiranjivSharma

**Comment by chiranjivSharma** [comment]
Got it after installing drivers it is not crashing
