### ISSUE TITLE
Bug: if jwt token expires logout user automatically 

### ISSUE THREAD

**Issue by amhsirak** [getmaxun/maxun#141]
Reported by @blazingbhavneek

**Comment by blazingbhavneek** [comment]
Additional information: Post logout, user is not directed back to login page but keeps on the dashboard and gives a "jwt error" in console while trying to enter browser mode

**Comment by amhsirak** [comment]
fixed in <a href="https://github.com/getmaxun/maxun/releases/tag/v0.0.2">v0.0.2</a>
