### ISSUE TITLE
CORS setup can't seem to work in hosted environment

### ISSUE THREAD

**Issue by publicvirtualvoid** [getmaxun/maxun#155]
I could be missing something, but I don't think this will ever work in a hosted environment. 
Does this need to pull the FE path from ENV?

https://github.com/getmaxun/maxun/blob/c9dc44884b46593d93e3dd1ed6dd81c078c774e1/server/src/server.ts#L22-L27

**Comment by AmitChauhan63390** [comment]
once it is hosted then only we can provide the link

**Comment by amhsirak** [comment]
@publicvirtualvoid what's your configuration to self host? We currently have provided local development infrastructure and in the next release will help users to self host. 

Are you running it on a remote server and have set up a reverse proxy?

**Comment by publicvirtualvoid** [comment]
I run everything behind traefik and use docker compose labels to configure each service.
I think the code just needs to be changed to pull from an env var instead.

**Comment by amhsirak** [comment]
@publicvirtualvoid I'm working on setting up self-hosted infrastructure. Should be available by this weekend.

**Comment by amhsirak** [comment]
fixed in #223
