### ISSUE TITLE
Feat: Show notification on robot delete with existing runs

### ISSUE THREAD

**Issue by amhsirak** [getmaxun/maxun#171]
It is not possible to delete a robot with existing runs. If the user wants to delete a robot, they should delete all associated runs. 

We should show a notification for the same everytime a user tries to delete a robot.

**Comment by AmitChauhan63390** [comment]
It was fixed but for some reason it's not working again after the new release

**Comment by amhsirak** [comment]
@AmitChauhan63390 can you take a look what happened?

**Comment by AmitChauhan63390** [comment]
@amhsirak  ok

**Comment by naveenpan09** [comment]
@amhsirak closing this as I can see it. If does not work, re-open it
