### ISSUE TITLE
本地运行老是出现service crashed

### ISSUE THREAD

**Issue by Echo-miao** [getmaxun/maxun#174]

**Comment by Echo-miao** [comment]
![image](https://github.com/user-attachments/assets/ee77b1ad-abe8-46ff-ae76-dd194525e223)

**Comment by amhsirak** [comment]
Hey @Echo-miao, as you can see in your postgres url, all details are undefined. This means your .env isn't being picked. Can you share more about your setup? Have you set your db credentials in .env?

**Comment by Echo-miao** [comment]
> Hey @Echo-miao, as you can see in your postgres url, all details are undefined. This means your .env isn't being picked. Can you share more about your setup? Have you set your db credentials in .env?

好的，十分感谢，现在已经正常的跑起来了，
