### ISSUE TITLE
抓取的网页怎么添加鉴权

### ISSUE THREAD

**Issue by Echo-miao** [getmaxun/maxun#175]
抓取的网页需要鉴权才能显示，怎么添加鉴权信息呢

**Comment by amhsirak** [comment]
@Echo-miao go to localhost:5173/register, add your credentials. It will automatically log you in.

**Comment by Echo-miao** [comment]
If you want to login to scrape: we're launching this soon. You can track the progress here: https://github.com/getmaxun/maxun/issues/55
对，我想要实现的就是这个，需要登录后才能抓取，这个对于使用功能十分重要，需要能尽快实现，

**Comment by amhsirak** [comment]
@Echo-miao sure. Can you pls upvote the issue so we know this is of higher priority.

I'll close this issue for now.

Thank you!
