### ISSUE TITLE
Documentation deficiency

### ISSUE THREAD

**Issue by shungabubus** [getmaxun/maxun#182]
Hello,

Not sure how it is with docker, but for regular use I'd really add a few key points (might be too obvious, but not for everyone):
before **_the last step_** you should insert a few steps (actually it would be amazing to add also the revision of .env, and outstanding to provide references to install the standard dependencies)
# get back to the root directory
cd ..

# make sure playwright is properly initialized
npx playwright install
npx playwright install-deps

_**# start frontend and backend together
npm run start**_

**Comment by shungabubus** [comment]
never mind

**Comment by shungabubus** [comment]
never mind

**Comment by amhsirak** [comment]
@shungabubus If you've faced issues with setting up the and using the software, it doesn't mean the software isn't programmed well. There are organizations and independent users using us, extracting thousands of rows of data everyday.

If you face issues, it's best to ask for help - a lot of people have done that to only find they made some  silly mistakes on their end.
