### ISSUE TITLE
Dude, we have applications for the same usecase

### ISSUE THREAD

**Issue by duzgunberke** [getmaxun/maxun#220]
Yes, I see that we are making very close applications that serve a similar purpose. I was thinking of marketing it as saas at first rather than releasing it opensource. Then I sold it to a CRM ERP company together with the source codes, it was tiring to deal with it alone, frankly :D

**https://www.ddexs.com** this was the site I made when I was thinking of marketing it as saas. Of course you can't see the back panels and stuff. If you want, I can join collabs and make a nice promotion site for this application :) I also have suggestions about new features that can be added, I can show how it works from the application I sell.

**Comment by amhsirak** [comment]
@duzgunberke mail me at karishmashuklaa [at] gmail [dot] com
Also, edited the issue title to avoid confusion of plagiarism
