### ISSUE TITLE
Feat: multi-language support.

### ISSUE THREAD

**Issue by ruanjunmin** [getmaxun/maxun#240]
Feat: multi-language support. 
I hope maxun can add multi-language support, mainly Chinese. I am from Hong Kong.

**Comment by amhsirak** [comment]
@ruanjunmin this is already been worked on, being tracked here: https://github.com/getmaxun/maxun/issues/184

**Comment by ruanjunmin** [comment]
> @ruanjunmin this is already been worked on, being tracked here: #184 PR for the same: #242

Oh, I see. Thanks
