### ISSUE TITLE
Docker - Can't register

### ISSUE THREAD

**Issue by roadkingvrod** [getmaxun/maxun#283]
I am up and running with Docker, with all services working. I can brwose to both the frontend and backend.  However, when I go to register, it just hangs and says Loading.  It never moves past that.  Any ideas? Nothing of value in the docker logs.

**Comment by amhsirak** [comment]
@roadkingvrod share you `.env` file. Have you followed all the steps here: https://github.com/getmaxun/maxun?tab=readme-ov-file#docker-compose?

**Comment by roadkingvrod** [comment]
I was able to resolve once I dug through discord.  Closing.  Thanks!

**Comment by harrymoo** [comment]
> I was able to resolve once I dug through discord. Closing. Thanks!

Hello, I've encountered the same issue. Could you tell me how to resolve it?

**Comment by James4Ever0** [comment]
Would you please share the details on how to fix this issue? Also how to enable verbose logging in `.env` file?
