### ISSUE TITLE
Feature: Extract behind login

### ISSUE THREAD

**Issue by amhsirak** [getmaxun/maxun#55]

**Comment by jontstaz** [comment]
Would be extremely useful for FB Marketplace just to name 1 example. I tried logging in but of course it starts a fresh session during the actual runtime so it was fruitless. Even if it were able to accept cookies it would be excellent. I will see how easily I can modify it. Will create a PR if successful.

**Comment by amhsirak** [comment]
@jontstaz great! do reach out to me on Discord (username: karishmashukla) or mail me at karishmashuklaa [at] gmail [dot] com if you need help 👍

**Comment by amhsirak** [comment]
Completed in #229
