### ISSUE TITLE
App startup problems with Docker

### ISSUE THREAD

**Issue by vukasinpetrovic** [getmaxun/maxun#96]
Hi, I've been trying to run the app but without success. I tried both master and dev branches, but there is the problem with communication between frontend and backend. 

On the master branch it was constantly giving exception that the port 8080 is being already used.
On the dev branch, when I go to /api-docs, it displays the swagger, but when I try to register, backend connection drops and it shuts down (I guess, because /api-docs no longer works).

Is this something you can fix quickly? I'm eager to try the app, but I'm stuggling to start it.

**Comment by amhsirak** [comment]
@vukasinpetrovic hi, yes we are working on the problem. Will be fixed in #93 by tomorrow 👍

**Comment by amhsirak** [comment]
@vukasinpetrovic can you try now? We've just added a new docker compose file

**Comment by vukasinpetrovic** [comment]
@amhsirak Thank you for the update, I'll try it now. Which branch should I use, dev or master?

**Comment by amhsirak** [comment]
@vukasinpetrovic 1. Use the master branch to build the compose 
2. If you get an error regarding a missing "start.sh" script (some users have reported this) remove the container and all volumes associated with it. It might be due to cache

Do let me know if this works

**Comment by vukasinpetrovic** [comment]
It works now, thank you for the update. Maybe only one more thing that could be useful for someone just starting the project, is an example .env file.
